version: '3.8'

services:
  tg-bot:
    image: ghcr.io/dimboknv/mexc:latest
    container_name: mexc-tg-bot
    hostname: mexc-tg-bot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    networks:
      - traefik_backend
    labels:
      - traefik.enable=true
      # Telegram webhook endpoint
      - traefik.http.services.mexc_tg_bot.loadbalancer.server.port=8080
      - traefik.http.routers.mexc_tg_bot.service=mexc_tg_bot
      - traefik.http.routers.mexc_tg_bot.entrypoints=websecure
      - traefik.http.routers.mexc_tg_bot.tls.certresolver=letsEncrypt
      - traefik.http.routers.mexc_tg_bot.rule=Host(`mexc-tg-bot.dimbok.dev`)
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DRY_RUN=${DRY_RUN:-true}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ADDRESS=0.0.0.0:8080
    volumes:
      - ./data/tg-bot:/app/data

  web-app:
    image: ghcr.io/dimboknv/mexc:latest
    container_name: mexc-web-app
    hostname: mexc-web-app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    networks:
      - traefik_backend
    labels:
      - traefik.enable=true
      # Web application
      - traefik.http.services.mexc_web_app.loadbalancer.server.port=8080
      - traefik.http.routers.mexc_web_app.service=mexc_web_app
      - traefik.http.routers.mexc_web_app.entrypoints=websecure
      - traefik.http.routers.mexc_web_app.tls.certresolver=letsEncrypt
      - traefik.http.routers.mexc_web_app.rule=Host(`mexc-web-bot.dimbok.dev`)
    environment:
      - ADDRESS=0.0.0.0:8080
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=/app/data/web_app.db
      - DRY_RUN=${DRY_RUN:-true}
      - API_URL=${API_URL}
    volumes:
      - ./data/web-app:/app/data

networks:
  traefik_backend:
    external: true
